# Generated by Django 6.0 on 2025-12-16 04:16

import app_autobuses.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2024)])),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=app_autobuses.models.autobus_imagen_path)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autobús',
                'verbose_name_plural': 'Autobuses',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('puesto', models.CharField(choices=[('conductor', 'Conductor'), ('auxiliar', 'Auxiliar'), ('administrativo', 'Administrativo'), ('gerente', 'Gerente')], max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=app_autobuses.models.empleado_imagen_path)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField()),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_estimada', models.CharField(help_text='Formato: 2h 30m', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['origen'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada_estimada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('asientos_disponibles', models.IntegerField()),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_autobuses.autobus')),
                ('conductor', models.ForeignKey(limit_choices_to={'puesto': 'conductor'}, on_delete=django.db.models.deletion.CASCADE, to='app_autobuses.empleado')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_autobuses.ruta')),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_numero', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('pagado', 'Pagado'), ('usado', 'Usado'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('codigo_boleto', models.CharField(max_length=10, unique=True)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_autobuses.pasajero')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_autobuses.viaje')),
            ],
            options={
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
